In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ratings = pd.read_csv('ratings.csv', encoding='latin-1')
new_df = pd.read_csv('movies.csv')

In [6]:
ratings.head()


userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [7]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)


In [8]:
print(train.shape)
print(test.shape)

(70585, 4)
(30251, 4)


In [9]:
df_movie_features = train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [10]:
df_movie_features.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  190215  190219  190221  191005  193565  193567  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193571  193579  193583  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 8536 columns]

In [11]:
dummy_train = train.copy()
dummy_test = test.copy()

In [12]:
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x>=1 else 1)
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

In [13]:
dummy_train = dummy_train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(1)

dummy_test = dummy_test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [14]:
dummy_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           0.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190215  190219  190221  191005  193565  193567  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193571  193579  193583  193609  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8536 columns]

In [15]:
dummy_test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  188189  188797  188833  189111  190209  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193573  193581  193585  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6089 columns]

In [16]:
from sklearn.metrics.pairwise import pairwise_distances

user_correlation = 1 - pairwise_distances(df_movie_features, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1.         0.03844192 0.08536622 ... 0.19408656 0.06817714 0.08887333]
 [0.03844192 1.         0.         ... 0.0422197  0.         0.0883011 ]
 [0.08536622 0.         1.         ... 0.01647758 0.         0.02845466]
 ...
 [0.19408656 0.0422197  0.01647758 ... 1.         0.07774534 0.21316911]
 [0.06817714 0.         0.         ... 0.07774534 1.         0.04861171]
 [0.08887333 0.0883011  0.02845466 ... 0.21316911 0.04861171 1.        ]]


In [17]:
user_correlation.shape

(610, 610)

In [18]:
movie_features = train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)

In [19]:
movie_features.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  190215  190219  190221  191005  193565  193567  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193571  193579  193583  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 8536 columns]

In [20]:
mean = np.nanmean(movie_features, axis=1)
df_subtracted = (movie_features.T-mean).T

In [21]:
df_subtracted.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1         -0.35     NaN   -0.35     NaN     NaN   -0.35     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5          0.40     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  190215  190219  190221  191005  193565  193567  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193571  193579  193583  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 8536 columns]

In [22]:
from sklearn.metrics.pairwise import pairwise_distances

# User Similarity Matrix
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[ 1.          0.00694602  0.00160449 ...  0.08373762 -0.03376757
   0.01625135]
 [ 0.00694602  1.          0.         ...  0.00263096  0.
   0.02505163]
 [ 0.00160449  0.          1.         ... -0.00666446  0.
   0.02409337]
 ...
 [ 0.08373762  0.00263096 -0.00666446 ...  1.          0.02601342
   0.03271935]
 [-0.03376757  0.          0.         ...  0.02601342  1.
  -0.04036397]
 [ 0.01625135  0.02505163  0.02409337 ...  0.03271935 -0.04036397
   1.        ]]


In [23]:
user_correlation[user_correlation<0]=0
user_correlation

array([[1.        , 0.00694602, 0.00160449, ..., 0.08373762, 0.        ,
        0.01625135],
       [0.00694602, 1.        , 0.        , ..., 0.00263096, 0.        ,
        0.02505163],
       [0.00160449, 0.        , 1.        , ..., 0.        , 0.        ,
        0.02409337],
       ...,
       [0.08373762, 0.00263096, 0.        , ..., 1.        , 0.02601342,
        0.03271935],
       [0.        , 0.        , 0.        , ..., 0.02601342, 1.        ,
        0.        ],
       [0.01625135, 0.02505163, 0.02409337, ..., 0.03271935, 0.        ,
        1.        ]])

In [24]:
user_predicted_ratings = np.dot(user_correlation, movie_features.fillna(0))
user_predicted_ratings

array([[1.58446164e+01, 5.54354123e+00, 7.08245905e+00, ...,
        0.00000000e+00, 0.00000000e+00, 2.80275213e-02],
       [5.07686451e+00, 2.06757205e+00, 6.00874556e-01, ...,
        1.81453987e-02, 1.81453987e-02, 0.00000000e+00],
       [2.24241909e+00, 1.17788776e+00, 2.90450622e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.90584218e+01, 1.02243416e+01, 6.91134419e+00, ...,
        2.06953826e-02, 2.06953826e-02, 3.14163689e-02],
       [1.90831554e+01, 8.84849001e+00, 4.23018218e+00, ...,
        0.00000000e+00, 0.00000000e+00, 8.24765355e-02],
       [2.68340188e+01, 1.02826443e+01, 4.23972094e+00, ...,
        1.25133258e-01, 1.25133258e-01, 5.45579834e-01]])

In [25]:
user_predicted_ratings.shape


(610, 8536)

In [26]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

movieId    1         2         3         4         5         6         7       \
userId                                                                          
1        0.000000  5.543541  0.000000  0.094025  1.916126  0.000000  2.631891   
2        5.076865  2.067572  0.600875  0.031692  0.584751  1.731990  0.393717   
3        2.242419  1.177888  0.290451  0.013938  0.123168  1.608382  0.156013   
4        7.362739  3.797650  2.323971  0.178680  1.499134  3.662610  2.192954   
5        0.000000  8.908434  3.050563  0.389251  3.424406  7.754833  4.715943   

movieId    8         9         10      ...    190215    190219    190221  \
userId                                 ...                                 
1        0.341030  0.247799  6.278434  ...  0.023942  0.015961  0.015961   
2        0.090132  0.048347  1.573140  ...  0.000000  0.000000  0.000000   
3        0.027674  0.019174  1.574436  ...  0.000000  0.000000  0.000000   
4        0.074205  0.360735  3.787689  ...  0.000000  0.000000  0.000000   
5        0.303140  1.036136  7.514680  ...  0.186165  0.124110  0.124110   

movieId   191005    193565    193567    193571    193579    193583    193609  
userId                                                                        
1        0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.028028  
2        0.02333  0.018145  0.015553  0.020738  0.018145  0.018145  0.000000  
3        0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
4        0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
5        0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.086721  

[5 rows x 8536 columns]

In [27]:
user_final_rating.iloc[1].sort_values(ascending=False)[0:5]

C:\Users\gaura\AppData\Local\Temp\ipykernel_6296\2825511131.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  user_final_rating.iloc[1].sort_values(ascending=False)[0:5]


movieId
356     9.838672
318     8.903198
2571    8.521299
2959    7.644745
7153    7.622569
Name: 2, dtype: float64

In [31]:
movies_list = sorted(list(user_predicted_ratings), reverse = True, key = lambda x:x[1])[1:6]

for i in movies_list:
    print (new_df.iloc[i[0]].title)
    

TypeError: Cannot index by location index with a non-integer key

In [ ]:
user_final_rating.iloc[10].sort_values(ascending=False)[0:5]

In [ ]:
movie_features = train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).T

movie_features.head()

In [ ]:
mean = np.nanmean(movie_features, axis=1)
df_subtracted = (movie_features.T-mean).T

In [ ]:
df_subtracted.head()

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances

#Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

In [ ]:
item_correlation[item_correlation<0]=0
item_correlation

In [ ]:
item_predicted_ratings = np.dot((movie_features.fillna(0).T),item_correlation)
item_predicted_ratings

In [ ]:
item_predicted_ratings.shape

In [ ]:
dummy_train.shape

In [ ]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

In [ ]:
item_final_rating.iloc[61].sort_values(ascending=False)[0:10]

In [ ]:
item_final_rating.shape

In [ ]:
item_final_rating.iloc[89].sort_values(ascending=False)[0:5]

In [ ]:
test_movie_features = test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)
mean = np.nanmean(test_movie_features, axis=1)
test_df_subtracted = (test_movie_features.T-mean).T

# User Similarity Matrix
test_user_correlation = 1 - pairwise_distances(test_df_subtracted.fillna(0), metric='cosine')
test_user_correlation[np.isnan(test_user_correlation)] = 0
print(test_user_correlation)

In [ ]:
test_user_correlation[test_user_correlation<0]=0
test_user_predicted_ratings = np.dot(test_user_correlation, test_movie_features.fillna(0))
test_user_predicted_ratings

In [ ]:
test_user_final_rating = np.multiply(test_user_predicted_ratings,dummy_test)

In [ ]:
test_user_final_rating.head()

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = test_user_final_rating.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

In [ ]:
test_ = test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)

In [ ]:
total_non_nan = np.count_nonzero(~np.isnan(y))

In [ ]:
rmse = (sum(sum((test_ - y )**2))/total_non_nan)**0.5
print(rmse)

In [ ]:
test_movie_features = test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).T

mean = np.nanmean(test_movie_features, axis=1)
test_df_subtracted = (test_movie_features.T-mean).T

test_item_correlation = 1 - pairwise_distances(test_df_subtracted.fillna(0), metric='cosine')
test_item_correlation[np.isnan(test_item_correlation)] = 0
test_item_correlation[test_item_correlation<0]=0

In [ ]:
test_item_correlation.shape

In [ ]:
test_movie_features.shape

In [ ]:
test_item_predicted_ratings = (np.dot(test_item_correlation, test_movie_features.fillna(0))).T
test_item_final_rating = np.multiply(test_item_predicted_ratings,dummy_test)
test_item_final_rating.head()

In [ ]:
test_item_final_rating

In [ ]:
test_ = test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = test_item_final_rating.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))


test_ = test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)

total_non_nan = np.count_nonzero(~np.isnan(y))

In [32]:
rmse = (sum(sum((test_ - y )**2))/total_non_nan)**0.5
print(rmse)

NameError: name 'test_' is not defined

In [ ]:
test_item_final_rating.iloc[29].sort_values(ascending=False)[0:5]

In [ ]:
import pickle as pl

In [ ]:
user_final_rating.iloc[84].sort_values(ascending=False)[0:5]